# Generated by Django 5.0.4 on 2024-05-02 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodApp', '__first__'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custom', models.ForeignKey(blank=True, default=(1, 'toppings', 4.2), on_delete=django.db.models.deletion.CASCADE, to='foodApp.custom')),
                ('standard', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='foodApp.pizzas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.user')),
            ],
        ),
    ]
