# Generated by Django 5.0.4 on 2024-05-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0003_alter_pizzas_imoge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzas',
            name='imoge',
        ),
        migrations.AddField(
            model_name='pizzas',
            name='image',
            field=models.CharField(default='basic_pizza.jpeg', max_length=30),
            preserve_default=False,
        ),
    ]
