# Generated by Django 5.0.4 on 2024-05-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0004_remove_pizzas_imoge_pizzas_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='id',
            new_name='customId',
        ),
        migrations.RenameField(
            model_name='custom',
            old_name='price',
            new_name='customPrice',
        ),
    ]
