# Generated by Django 5.0.4 on 2024-05-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0005_rename_id_custom_customid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='customId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
