# Generated by Django 5.0.4 on 2024-05-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0006_alter_custom_customid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='customId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
